name: AGLint

on:
  workflow_dispatch:
  push:
    paths:
      - "lists/sources/**/*.txt"
      - ".aglintrc.*"
      - "package.json"
      - "bun.lockb"
  pull_request:
    paths:
      - "lists/sources/**/*.txt"
      - ".aglintrc.*"
      - "package.json"
      - "bun.lockb"

permissions:
  contents: write

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Run AGLint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun add -D @adguard/aglint

      - name: Init AGLint config
        if: ${{ !hashFiles('.aglintrc.yml') && !hashFiles('.aglintrc.yaml') }}
        run: bunx aglint init

      - name: Run AGLint
        run: bunx aglint

      - name: Commit and push changes
        if: github.event_name != 'pull_request'
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "ci(linter): lint filter lists"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
