name: AGLint
env:
  NODE_VERSION: 20
on:
  workflow_dispatch:
  push:
    paths:
      - "lists/sources/**/*.txt"
      - ".aglintrc.*"
      - "package.json"
      - "package-lock.json"
  pull_request:
    paths:
      - "lists/sources/**/*.txt"
      - ".aglintrc.*"
      - "package.json"
      - "package-lock.json"

jobs:
  lint:
    name: Run AGLint
    runs-on: ubuntu-latest
    steps:
      - name: Check out to repository
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          check-latest: true
          cache: 'npm'
          package-manager-cache: true
      - name: Install dependencies
        run: npm install -D @adguard/aglint
        # Init if no config file present
      - name: Init
        shell: bash
        run: |
          [[ ! -f ".aglintrc.yml" || ! -f ".aglintrc.yaml" ]] && npx aglint init
      # If the linter found any errors, it will exit with a non-zero code, which will cause the job to fail
      - name: Run AGLint
        run: npx aglint
  
      - name: "Commit and push changes"
        shell: bash
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          # Check if there are any changes in the releases directory
          if ! git diff --quiet; then
            git add -A
            git commit -m "ci(linter): lint filter lists" -m "Built on $(date -u)"
            git push
          else
            echo "No changes to commit. Compiled lists are up-to-date."
          fi
